CREATE DATABASE QUANLICHAMCONG
GO

USE QUANLICHAMCONG
GO

CREATE TABLE NHANVIEN 
(
MANV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
NGAYSINH DATE NOT NULL,
LUONG INT NOT NULL,
GTINH VARCHAR(10) NOT NULL
)

CREATE TABLE DUAN
(
MADA VARCHAR(10) PRIMARY KEY,
TENDA NVARCHAR(50) NOT NULL,
NAMBATDAU INT NOT NULL
)

CREATE TABLE CHAMCONG
(
MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
MADA VARCHAR(10) FOREIGN KEY REFERENCES DUAN(MADA),
SOGIO INT NOT NULL
)

INSERT INTO NHANVIEN
VALUES
('N01', N'LÊ VĂN TÈO', '2002/03/01', 19000000, 'NAM'),
('N02',N'NGỌC GIÀU', '1998/03/03', 6000000,'NAM'),
('N03',N'ĐẶNG THỊ HIẾU', '1996/01/05', 60000000, 'NU')

INSERT INTO DUAN
VALUES 
('D1', N'PHẦN MỀM DẠY ONLINE', 2021),
('D2', N'MẠNG AGENT', 2022),
('D3', N'QUẢN LÍ SÁCH', 2020)

INSERT INTO CHAMCONG
VALUES
('N01', 'D1', 220),
('N03', 'D1', 200),
('N01', 'D3', 90)

SELECT * FROM NHANVIEN
SELECT * FROM DUAN
SELECT * FROM CHAMCONG

--CÂU 2

SELECT MANV AS N'MÃ NHÂN VIÊN', HOTEN AS N'HỌ TÊN', NGAYSINH AS N'NGÀY SINH' FROM NHANVIEN WHERE LUONG > 7000000 AND GTINH = 'NU'

--CÂU 3

SELECT DA.MADA, DA.TENDA FROM
NHANVIEN AS NV JOIN CHAMCONG AS CC 
ON NV.MANV = CC.MANV
JOIN DUAN AS DA ON CC.MADA = DA.MADA
WHERE NV.HOTEN LIKE N'%NGỌC GIÀU%'

--CÂU 4

SELECT NV.MANV, NV.HOTEN, SUM(CC.SOGIO) FROM
NHANVIEN AS NV JOIN CHAMCONG AS CC
ON NV.MANV = CC.MANV 
GROUP BY NV.MANV, NV.HOTEN,CC.SOGIO
HAVING SUM(CC.SOGIO) > 90

-- CÂU 5

SELECT NV.MANV, NV.HOTEN, COUNT(CC.MADA) FROM
NHANVIEN AS NV JOIN CHAMCONG AS CC
ON NV.MANV = CC.MANV 
GROUP BY NV.MANV, NV.HOTEN,CC.MADA

-- CÂU 6:

INSERT INTO NHANVIEN (MANV, HOTEN, NGAYSINH, LUONG, GTINH)
VALUES ('N03',N'ĐẶNG THỊ TIÊN', '1997/04/04', 40000000, 'NU')

-- CÂU 7

UPDATE DUAN SET NAMBATDAU = '2019' WHERE TENDA = N'MẠNG AGENT'

DROP TABLE DUAN

--CÂU 8

DELETE FROM DUAN 